# PDN Impedance Optimization Tool - User Configuration
# デカップリングコンデンサ自動選択のための設定ファイル

[frequency]
# 周波数グリッド設定
f_start = 1e2      # 開始周波数 [Hz]
f_stop = 5e8       # 終了周波数 [Hz]
num_points_per_decade = 768  # 10倍周波数ごとの点数

# 評価帯域
f_L = 1e3          # 下限周波数 [Hz]
f_H = 1e8          # 上限周波数 [Hz]

[target]
# 目標インピーダンス
z_target = 10e-3   # フラット目標 [Ω]

# カスタムマスク（オプション）
# 周波数とインピーダンスのペアで定義
z_custom_mask = [
    [1e3, 10e-3],
    [5e3, 10e-3],
    [2e4, 8e-3],
    [5e4, 8e-3],
    [2e6, 25e-3],
    [1e8, 1.3e0]
]

[pdn_parasitic]
# PDN寄生成分
R_vrm = 10e-3      # VRM抵抗 [Ω]
L_vrm = 10e-9      # VRMインダクタンス [H]
R_sN = 0.5e-3      # Spreading抵抗（デカップリングコンデンサ用） [Ω]
L_sN = 0.5e-9      # Spreadingインダクタンス（デカップリングコンデンサ用） [H]
L_mntN = 0.5e-9    # デフォルトマウントインダクタンス [H]
R_s = 0.5e-3       # Spreading抵抗 [Ω]
L_s = 1e-9         # Spreadingインダクタンス [H]
R_v = 0.5e-3       # Via抵抗 [Ω]
L_v = 1e-9         # Viaインダクタンス [H]
R_p = 5e-3         # プレーナ抵抗 [Ω]
C_p = 10e-12       # プレーナ容量 [F]
tan_delta_p = 0.02 # 誘電正接

[spice]
dc_bias = 5.0      # DCバイアス電圧 [V]
model_path = "model"  # SPICEモデルディレクトリ

[search]
# 探索設定
max_total_parts = 16        # コンデンサ総数上限
min_total_parts_ratio = 0.3 # 最小総数比率（max_total_partsに対する比率）
top_k = 10                  # 上位候補数
shuffle_evaluation = true   # 評価順のシャッフル
buffer_limit = 1e6         # バッファサイズ上限

[weights]
# スコア重み（小さいほど良い）
weight_max = 0.9    # 最大値の重み
weight_area = 0.65  # 超過面積の重み
weight_mean = 0.5   # 平均値の重み
weight_anti = 0.35  # アンチレゾナンスの重み
weight_flat = 0.15  # フラットネスの重み
weight_under = -0.1 # 余裕面積の重み（負値）
weight_parts = 0    # 部品点数ペナルティの重み
weight_mc_worst = 1.0  # Monte Carlo最悪値の重み

[monte_carlo]
# Monte Carlo設定
mc_enable = true    # Monte Carlo評価の有効化
mc_samples = 64     # サンプル数
tol_C = 0.2        # 容量公差（±20%）
tol_ESR = 0.2      # ESR公差（±20%）
tol_ESL = 0.2      # ESL公差（±20%）
mlcc_derating = 0.15  # MLCCディレーティング（15%）

[system]
# システム設定
seed = 1234        # 乱数シード
max_vram_ratio_limit = 0.5  # VRAM使用率上限
cuda = 0           # 使用するGPU番号
dtype_c = "complex64"  # 複素数精度
dtype_r = "float32"    # 実数精度
force_numpy = false    # NumPy強制使用（GPU無効化）

[gui]
# GUI設定
use_gui = true     # GUI使用
server_port = 8501 # Streamlitポート番号
dark_theme = true  # ダークテーマ
language = "jp"    # 言語（jp/en）

[output]
# Excel出力設定
excel_path = "out"           # 出力ディレクトリ
excel_name = "dcap_result"   # ファイル名プレフィックス

# コンデンサリスト
# SPICEモデルがある場合はpathを指定、ない場合はRLC値を直接指定
[[capacitors]]
name = "C_0603_0.1u"
C = 0.1e-6
ESR = 15e-3
ESL = 0.5e-9

[[capacitors]]
name = "C_0603_1u"
C = 1e-6
ESR = 10e-3
ESL = 0.5e-9

[[capacitors]]
name = "C_0603_4.7u"
C = 4.7e-6
ESR = 8e-3
ESL = 0.5e-9

[[capacitors]]
name = "C_1608_10u"
C = 10e-6
ESR = 5e-3
ESL = 0.8e-9
L_mnt = 0.6e-9  # カスタムマウントインダクタンス

[[capacitors]]
name = "C_2012_22u"
C = 22e-6
ESR = 3e-3
ESL = 1.0e-9

[[capacitors]]
name = "C_2012_47u"
C = 47e-6
ESR = 2.5e-3
ESL = 1.2e-9

[[capacitors]]
name = "C_3216_100u"
C = 100e-6
ESR = 2e-3
ESL = 1.5e-9

# SPICEモデルを使用する場合の例
# [[capacitors]]
# name = "MURATA_GRM188"
# path = "GRM188R60J106ME47.mod"  # model/GRM188R60J106ME47.mod
# L_mnt = 0.5e-9